public class Man {
    public static void main(String[] args) {
        System.out.println("Wrong guess 0: (Game Start)");
        System.out.println("   +------+");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 1:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 2:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 3:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |      |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 4:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |     /|");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 5:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (Ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 6:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (Ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 7:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (Ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |     /");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
        System.out.println("Wrong guess 8: (Game Over)");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (X)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |     / \\");
        System.out.println("  _|_");
        System.out.println("=/=|=\\=========");
        System.out.println();
    }
}
