public class Man {
    public static void main(String[] args) {
        System.out.println("Score 0:");
        System.out.println("   +------+");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 1:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 2:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 3:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |      |");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 4:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |     /|");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 5:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 6:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 7:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |     /");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 8:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |     / \\");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
        System.out.println();
        System.out.println("Score 8:");
        System.out.println("   +------+");
        System.out.println("   |      |");
        System.out.println("   |     (Ӧ)");
        System.out.println("   |     /|\\");
        System.out.println("   |      |");
        System.out.println("   |     / \\");
        System.out.println("  _|_");
        System.out.println("=/=|=\\========");
    }
}
